Implement docs feedback from heuristic walkthrough
AlexsLemonade/scpca-downstream-analyses pull request #223
Opened 2022-09-27 13:24 UTC by cbethell

**Issue Addressed**
NA

**What is the purpose of these changes?**

This PR further incorporates the README feedback left on PR #221 and is therefore stacked on that PR's branch.

**What changes did you make?**

I mostly incorporated the comments left on PR #221, with exception of providing link to example output files as suggested in https://github.com/AlexsLemonade/scpca-downstream-analyses/pull/221/files#r972402774, as we do not save the output files in the repo.

I also left some comments on that PR where I was unable to fully address a specific suggestion.

**Any comments, concerns, or questions important for reviewers**
- Does this PR appropriately address the comments left on PR #221?
- Should we maybe include screenshots of the output files since we cannot actually link to the output files?
- I was also not sure what was meant by adding some "possible version of the cmd" as suggested in https://github.com/AlexsLemonade/scpca-downstream-analyses/pull/221/files#r972388626.

**Checklist**

Place an `x` in all boxes that you have completed.

- [ ] I have run the most recent version of the code
- [ ] If I am adding in reports or generating any plots, I have reviewed the necessary reports
- [x] I have added all necessary documentation (if applicable)

2022-09-28 14:34 UTC, dvenprasad requested changes
The changes are looking good! 

I also responded to [this comment](https://github.com/AlexsLemonade/scpca-downstream-analyses/pull/221#discussion_r981241892) on the other PR.  We can continue the discussion on this PR if that is easier. 

I left a few comments about minor formatting changes to make it easier to scan and read.

2022-09-28 14:34 UTC, dvenprasad commented on README.md
> +There are two expected output files thay will be associated with each provided `SingleCellExperiment` object and `library_id`: a processed `SingleCellExperiment` object containing normalized data and
```suggestion
**Output Files**
There are two expected output files thay will be associated with each provided `SingleCellExperiment` object and `library_id`: 
- A processed `SingleCellExperiment` object containing normalized data and clustering results
- A summary HTML report detailing:
    - Filtering of low quality cells
    - Dimensionality reduction
    - Clustering that was performed within the workflow. 

See the [expected output section](#expected-output) for more information on these output files.
```

Breaking it up so it is easier to scan. Please correct phrasing to fit this format, if needed.

2022-09-28 14:34 UTC, dvenprasad commented on README.md
> +We have provided a snakemake [configuration file](https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html), [`config.yaml`](https://github.com/AlexsLemonade/scpca-downstream-analyses
```suggestion
We have provided an example [snakemake configuration file](https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html), [`config.yaml`](https://github.com/AlexsLemonade/scpca-downstream-analyses/blob/main/config.yaml) which sets the defaults for all parameters needed to run the workflow.
```

2022-09-28 14:34 UTC, dvenprasad commented on README.md
> +3. A project metadata tab-separated value (TSV) file containing relevant information about your data necessary for processing (see more on this in the ["Metadata file format" section](#metadata-file-
Maybe we can link the example metadata file here as well. Thinking about users who are coming back to the documentation after while. It would be nice for them to find what they might want without too much bouncing from section to section.

Could we also mention need to a config file here and link to the example file?

2022-09-28 14:34 UTC, dvenprasad commented on README.md
> +As described in the Snakemake instructions, the recommended way to install snakemake is using the conda package manager.
Can we make these two line more concise? Perhaps something like this:

```suggestion
Snakemake recommends installing it is using the conda package manager. 
```

2022-09-28 14:34 UTC, dvenprasad commented on README.md
> +Therefore, you will want to first install [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html) (we recommend the Miniconda installation).
```suggestion
Here are the instructions to install [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html) 
We recommend the Miniconda installation.
```

2022-10-03 18:52 UTC, cbethell commented
Thanks for the feedback @dvenprasad!! I added an example of that command you mentioned in https://github.com/AlexsLemonade/scpca-downstream-analyses/pull/221#discussion_r981241892 and _believe_ I implemented all of your suggestions here -- let me know what you think of things now!

2022-10-05 13:57 UTC, dvenprasad approved these changes
Just caught a little mismatched phrase. But other than that it looks good! Thank you!

🥭 🥭 🥭

2022-10-05 13:57 UTC, dvenprasad commented on README.md
> +After installing conda has been installed, you can follow the steps below to set up the bioconda and conda-forge channels and install Snakemake in an isolated environment:
Whoop rephrasing to smooth it out. 

```suggestion
After installing conda, you can follow the steps below to set up the bioconda and conda-forge channels and install Snakemake in an isolated environment:
```

2022-10-05 15:25 UTC, merged